### PR TITLE
tests now pass on 1.0

### PR DESCRIPTION
**Pull request by ExpandingMan**
It would be useful if this could be tagged relatively soon after this is merged, because it may be needed by JuMP 0.18 to pass travis tests.

### CODE REVIEW

**Comment by ExpandingMan** [comment]
Ok, should be good to go.  Note that the failure on 1.0 is because of the script in `.travis.yml`.  Now one must do `import Pkg` and `Pkg.dir` is deprecated.  I'm not sure why line 19 of `.travis.yml` needs to be there.  If you want we can delete or change it, otherwise the failure on 1.0 is probably fine because we are successful without warnings on 0.7.

**Comment by mlubin** [comment]
It's not good practice to leave the CI failing. Please either disable testing on 1.0 (with a comment explaining why) or fix the failure (see other packages that are passing on 1.0 on Travis).

**Comment by ExpandingMan** [comment]
Thankfully I just realized that even in 1.0 `Pkg.dir` works with a warning (thought it was supposed to throw an error) so that should make the fixes very easy.

Besides, it would have been rather sad if the 1.0 tests failed when the title of my PR was "now passing on 1.0" :laughing:

**Comment by mlubin** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16911

**Pull request merged**
