### PR TITLE
fix for NaNs in ifelse

### PR DESCRIPTION
**Pull request by mlubin**
@vepiteski, could you confirm this fixes your issue?

### CODE REVIEW

**Comment by vepiteski** [comment]
@mlubin Not totally. Evaluation using 2*log(x-2) is now the same as log + log. However, both (2*log and log+log) still produce a NaN at x=2.0. The derivative at 2.0 should be 0.

**Comment by mlubin** [comment]
@vepiteski, try again now

**Comment by vepiteski** [comment]
@mlubin Works OK on my example. Will the fix be available on master soon? Thank you for your super quick fix!

**Comment by mlubin** [comment]
Thanks for confirming. Now it's on master :)

**Pull request merged**
