### PR TITLE
Refactor eval_univariate to avoid depending on Lazy.jl

### PR DESCRIPTION
**Pull request by tkelman**
Also switch to a binary nested if - worth checking if this part is good or bad for performance. Could make it linear, the same as `Lazy.@switch`, if this turns out to hurt. Are there benchmarks somewhere?

### CODE REVIEW

**Comment by tkelman** [comment]
Nightly failure looks like Graphs.jl's fault.

**Comment by tkelman** [comment]
Comparison of expanded code, before and after: https://gist.github.com/413b10ca3e8d20e5c17c77b1f376d2f6

**Comment by mlubin** [comment]
Probably the most convincing benchmark would be the [acpower](https://github.com/mlubin/JuMPSupplement/tree/master/acpower) model we used for our paper.

**Comment by tkelman** [comment]
Old enough that it has a bunch of deprecations and needed some `int(...)` -> `parse(Int, ...)` replacements to run at all on 0.5, but both generation time and function evaluation time look about the same at all 3 sizes.

**Pull request merged**
